name: 'CI'
on:
  push:
    branches:
      - '**'
jobs:
  build:
    runs-on: [self-hosted, linux, x64, gpu]
    steps:
      - uses: actions/checkout@v3
      - uses: npm/actions-setup@v2
        with:
          version: 7
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: npm
      - run: npm install --frozen-lockfile
      - run: npm run lint && npm run build
